### ISSUE TITLE
Ignition Setting is not persistence. 

### ISSUE THREAD

**Issue by pxlcodes** [spatie/laravel-ignition#34]
Saving Setting on error page will not be persistence on next request cycle.

**Comment by freekmurze** [comment]
Did you create that file via the error page itself (cogwheel in the top right corner).

**Comment by pxlcodes** [comment]
Yes changed theme and editor both from cogwheel (Ignition Settings) and saved. Still there is no change.
However I edited config/ignition.php and I seems working fine.

**Comment by titantwentyone** [comment]
Also having the same issue. Unsure if related but my Chrome console shows:

```
pages:3787 Warning: Each child in a list should have a unique "key" prop.
```
Is there any guidance on the format of the json so we can create it manually?

**Comment by nickdekruijk** [comment]
I had this issue too, creating an empty `touch ~/.ignition.json` solved it for me.
Can't ignition create this file if it's not there?

**Comment by AlexVanderbist** [comment]
Hi all, we've updated the ignition package a while ago to automatically create the settings file, should it be missing. Running `composer update` should automatically pull in this new version of Ignition and its dependencies.

Thanks for everyone's input on this!

**Comment by warmwhisky** [comment]
I still cannot use the Save Settings button. Only persists to dark mode when editing in config file.
Version 1.2.2

I tried creating .ignition.json manually but still not updating

Console error reads
```
workbox No route found for: /_ignition/update-config
```

**Comment by warmwhisky** [comment]
> It seems to work here. Maybe it's a permissions issue? Could you check if there is a config file created where Ignition says it will save your preferences?

I have no config file in home directory. However, when I click save on the error page from the cog it says "Saved!"

I'm running Ubuntu 22.04 and its not respecting System dark mode. though I think thats Ubuntu?

**Comment by penobit** [comment]
I have the same issue
after changing config and clicking on save button green `Saved!` message appears,
although network console logs a new request:  `POST /_ignition/update-config request ` 
and it's response is `false`
I also tried:
- created config file manually `$ touch ~/.ignition.json`
- i changed file permissions to 0777 and changed owner of the to current user with `www-data` group `chown USERNAME:www-data ~/.ignition.json`
- I even added `{ "editor": "vscode", "hide_solutions": false, "theme": "auto" }` to  `~/.ignition.json` contents

but got the same results (`false` as response of `/_ignition/update-config` request)

**Comment by penobit** [comment]
I found a workaround for this issue
I noticed that the library is looking for `/.ignition.json` file and without root permission it can't write to "/" directory
I also found out that library will use project's `.ignition.json` if exists.

so, for fixing this issue you should:
- Add `HOME="/path/to/project/root/directory"` to your .env file. so library will check for `${HOME}/.ignition.json` instead of `/.ignition.json` 
- Create a ignition config file `$ touch /path/to/project/root/directory/.ignition.json`
- Make sure the file has correct permissions and owner/group `sudo chmod 0777 /path/to/project/root/directory/.ignition.json && chown $(whoami):www-data /path/to/project/root/directory/.ignition.json`
- Now save your configuration through an error page and it will be saved
