### ISSUE TITLE
Solutions cannot be run from your current IP address.

### ISSUE THREAD

**Issue by karlhillx** [spatie/laravel-ignition#69]
I came across this error a lot today but am unsure what it means for my Amazon EC2 server. Any ideas?

Laravel: 9.4.1
PHP: 8.1
spatie/ignition: 1.2.3
spatie/laravel-ignition: 1.0.6

2022-03-09 16:38:00] local.ERROR: Solutions cannot be run from your current IP address. {"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\CannotExecuteSolutionForNonLocalIp(code: 0): Solutions cannot be run from your current IP address. at /var/www/html/vendor/spatie/laravel-ignition/src/Exceptions/CannotExecuteSolutionForNonLocalIp.php:14)
[stacktrace]
#0 /var/www/html/vendor/spatie/laravel-ignition/src/Http/Controllers/ExecuteSolutionController.php(48): Spatie\\LaravelIgnition\\Exceptions\\CannotExecuteSolutionForNonLocalIp::make()
#1 /var/www/html/vendor/spatie/laravel-ignition/src/Http/Controllers/ExecuteSolutionController.php(21): Spatie\\LaravelIgnition\\Http\\Controllers\\ExecuteSolutionController->ensureLocalRequest()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(48): Spatie\\LaravelIgnition\\Http\\Controllers\\ExecuteSolutionController->__invoke()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#7 /var/www/html/vendor/spatie/laravel-ignition/src/Http/Middleware/RunnableSolutionsEnabled.php(15): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Spatie\\LaravelIgnition\\Http\\Middleware\\RunnableSolutionsEnabled->handle()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(727): Illuminate\\Pipeline\\Pipeline->then()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(702): Illuminate\\Routing\\Router->runRouteWithinStack()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(666): Illuminate\\Routing\\Router->runRoute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(655): Illuminate\\Routing\\Router->dispatchToRoute()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()

**Comment by AlexVanderbist** [comment]
Hi @karlhillx, 

Sorry about that. To avoid any remote code execution vulnerabilities we've disabled the possibility to execute solutions from any non-local IP address. This will prevent anyone with access to your ec2 instance to execute solutions on your behalve.

I'd propose using an SSH tunnel to connect to your EC2 instance. This will allow you to interact with the PHP application as if it is installed on your local machine.

The code responsible for this gate check is right here: https://github.com/spatie/laravel-ignition/blob/271d25af87a3a6769bed613e98fd9c36d3a070e9/src/Http/Controllers/ExecuteSolutionController.php#L39-L52
We're always open for suggestions to improve this, thanks!

**Comment by chen900804** [comment]
@AlexVanderbist  I hope to configure the specified IP and execute the solution on my behave

**Comment by AlexVanderbist** [comment]
Hi @chen900804, out of curiosity: what's the use-case for this? Are you developing on a remote server? How are the fixed files getting from the remote server back into Git?

**Comment by axis80** [comment]
I'm not the previous commenter but here's my use case: I have a couple Ubuntu VPS servers (on DigitalOcean) which I use as development machines.  I use [rmate](https://github.com/textmate/rmate) to edit the remote files, and the bash CLI to check changes into git.  I find this much easier than working off of localhost, because a) I work from multiple desktop PCs in multiple locations; and b) my apps have a lot of incoming webhook and callback requests, and I would prefer to not have to set up a bunch of ngrok tunnels and/or dynamic DNS entries.

Anyway, the Laravel logs on my dev servers are filling up with this error message related to solutions.  It's not the end of the world but it does make it harder to debug my apps sometimes.  Possible fixes:

- An opt-out approach: you could add a config option (disabled by default) allowing people like me to suppress the "non-local IP" error messages.  
- An opt-in approach: you could make it so that by default, solutions are only suggestions.  Only if the user has explicitly entered their IP address into an allowlist do they become executable.

There's probably some better idea that isn't occurring to me right now.

**Comment by dr-roshyara** [comment]
I have the same problem in Digital Ocean however I cant find the cause of this error. What and How should I avoid this error. 
Running Server: Digital Ocean 
Running Machine: Ubuntu-20.04
Servertype: VPS

**Comment by gleb-svitelskiy** [comment]
If you are using this package in an application with enabled debug mode on a public webserver and you don't need the ability to run solutions from an error page - you can set `IGNITION_ENABLE_RUNNABLE_SOLUTIONS` environment variable to `false`. This will help to get rid of such exceptions in your error log.
These exceptions are most likely caused by attempts by third parties to exploit vulnerabilities.

**Comment by AlexVanderbist** [comment]
So as a TL;DR:

- don't set `APP_DEBUG=true` on any public server (unless you know what you're doing)
- if you really want to force solutions to run anywhere, set `IGNITION_ENABLE_RUNNABLE_SOLUTIONS=true` and `APP_ENV=local` but please know that this is a security risk!
- if you are inexplicably receiving the aforementioned exception in your logs: disable `APP_DEBUG=true` or set `IGNITION_ENABLE_RUNNABLE_SOLUTIONS=false`
- once again, please do no use `APP_DEBUG=true` anywhere else but on your local machine

**Comment by EmeMendez** [comment]
I have the same problem, any solutions?
